### ISSUE TITLE
What is filtering factor? 

### ISSUE THREAD

**Issue by sehrish777** [krishna1401/Digital-Image-Processing#1]
Hi There,
Can you please let me know what is the value of the filtering factor here? 
I am running this code, entering some integers as filtering factor values but it is throwing an error. Can you please guide me here? 

Thanks so much in advance!

**Comment by krishna1401** [comment]
Hi @sehrish777, I worked on this project around 3 years back and now I don't exactly remember the filtering factor. Sorry for the same but unable to help you here.
